tunnel:
  - Name: test-1
    ssh_Host: namejm.com
    ssh_Port: 2234
    S2C:
      - List.Interface: 10.1.3.200
        List.Port: 5900
        Dest.Interface: 10.1.3.100
        Dest.Port: 3389
      - List.Interface: 10.1.3.200
        List.Port: 5901
        Dest.Interface: 10.1.3.100
        Dest.Port: 3389